version: '3.8'

x-build-args: &build-args
  APP_USERNAME: guest
  PASSWORD: "Guest@123"
  CLUSTER_SECRET: 3ae87335896900efaba880bfc23c58e6f9263a2bc6aad4499b2a51fd275e48f3
  ADMIN_PASSWORD: Admin@123
  SWARM_KEY: 633ffede0baebe3b705a86621d4d490fa00e0666bdba9fe89ab41e895619b79c

services:
  node1:
    build:
      context: .
      args: *build-args
    container_name: node1
    hostname: node1
    networks:
      ipfsnet:
        ipv4_address: 172.18.0.11
    ports:
      - "2221:22"
    volumes:
      - node1_home:/home/guest

  node2:
    build:
      context: .
      args: *build-args
    container_name: node2
    hostname: node2
    networks:
      ipfsnet:
        ipv4_address: 172.18.0.12
    ports:
      - "2222:22"
    volumes:
      - node2_home:/home/guest

  node3:
    build:
      context: .
      args: *build-args
    container_name: node3
    hostname: node3
    networks:
      ipfsnet:
        ipv4_address: 172.18.0.13
    ports:
      - "2223:22"
    volumes:
      - node3_home:/home/guest

networks:
  ipfsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  node1_home:
  node2_home:
  node3_home:
