version: '3.8'

services:
  node1:
    build: .
    container_name: node1
    hostname: node1
    networks:
      ipfsnet:
        ipv4_address: 172.18.0.11
    ports:
      - "2221:22"
      - "4001:4001"
      - "5001:5001"
      - "8081:8080"
      - "9091:9096"
      - "9191:9094"
    volumes:
      - ./swarm.key:/swarm.key:ro
      - ./id_ed25519.pub:/id_ed25519.pub:ro
      - node1_home:/home/guest

  node2:
    build: .
    container_name: node2
    hostname: node2
    networks:
      ipfsnet:
        ipv4_address: 172.18.0.12
    ports:
      - "2222:22"
      - "4002:4001"
      - "5002:5001"
      - "8082:8080"
      - "9092:9096"
      - "9192:9094"
    volumes:
      - ./swarm.key:/swarm.key:ro
      - ./id_ed25519.pub:/id_ed25519.pub:ro
      - node2_home:/home/guest

  node3:
    build: .
    container_name: node3
    hostname: node3
    networks:
      ipfsnet:
        ipv4_address: 172.18.0.13
    ports:
      - "2223:22"
      - "4003:4001"
      - "5003:5001"
      - "8083:8080"
      - "9093:9096"
      - "9193:9094"
    volumes:
      - ./swarm.key:/swarm.key:ro
      - ./id_ed25519.pub:/id_ed25519.pub:ro
      - node3_home:/home/guest

networks:
  ipfsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  node1_home:
  node2_home:
  node3_home: